development:
  host: localhost
  database: skeleton_development

test:
  host: localhost
  database: skeleton_test

# set these environment variables on your prod server
production:
  host: localhost
  #port: 28017
  database: carrie_production
