require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LearningGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # LearningGroup. As you add validations to LearningGroup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LearningGroupsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all learning_groups as @learning_groups" do
      learning_group = LearningGroup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:learning_groups).should eq([learning_group])
    end
  end

  describe "GET show" do
    it "assigns the requested learning_group as @learning_group" do
      learning_group = LearningGroup.create! valid_attributes
      get :show, {:id => learning_group.to_param}, valid_session
      assigns(:learning_group).should eq(learning_group)
    end
  end

  describe "GET new" do
    it "assigns a new learning_group as @learning_group" do
      get :new, {}, valid_session
      assigns(:learning_group).should be_a_new(LearningGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested learning_group as @learning_group" do
      learning_group = LearningGroup.create! valid_attributes
      get :edit, {:id => learning_group.to_param}, valid_session
      assigns(:learning_group).should eq(learning_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LearningGroup" do
        expect {
          post :create, {:learning_group => valid_attributes}, valid_session
        }.to change(LearningGroup, :count).by(1)
      end

      it "assigns a newly created learning_group as @learning_group" do
        post :create, {:learning_group => valid_attributes}, valid_session
        assigns(:learning_group).should be_a(LearningGroup)
        assigns(:learning_group).should be_persisted
      end

      it "redirects to the created learning_group" do
        post :create, {:learning_group => valid_attributes}, valid_session
        response.should redirect_to(LearningGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved learning_group as @learning_group" do
        # Trigger the behavior that occurs when invalid params are submitted
        LearningGroup.any_instance.stub(:save).and_return(false)
        post :create, {:learning_group => {}}, valid_session
        assigns(:learning_group).should be_a_new(LearningGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LearningGroup.any_instance.stub(:save).and_return(false)
        post :create, {:learning_group => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested learning_group" do
        learning_group = LearningGroup.create! valid_attributes
        # Assuming there are no other learning_groups in the database, this
        # specifies that the LearningGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LearningGroup.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => learning_group.to_param, :learning_group => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested learning_group as @learning_group" do
        learning_group = LearningGroup.create! valid_attributes
        put :update, {:id => learning_group.to_param, :learning_group => valid_attributes}, valid_session
        assigns(:learning_group).should eq(learning_group)
      end

      it "redirects to the learning_group" do
        learning_group = LearningGroup.create! valid_attributes
        put :update, {:id => learning_group.to_param, :learning_group => valid_attributes}, valid_session
        response.should redirect_to(learning_group)
      end
    end

    describe "with invalid params" do
      it "assigns the learning_group as @learning_group" do
        learning_group = LearningGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LearningGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => learning_group.to_param, :learning_group => {}}, valid_session
        assigns(:learning_group).should eq(learning_group)
      end

      it "re-renders the 'edit' template" do
        learning_group = LearningGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LearningGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => learning_group.to_param, :learning_group => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested learning_group" do
      learning_group = LearningGroup.create! valid_attributes
      expect {
        delete :destroy, {:id => learning_group.to_param}, valid_session
      }.to change(LearningGroup, :count).by(-1)
    end

    it "redirects to the learning_groups list" do
      learning_group = LearningGroup.create! valid_attributes
      delete :destroy, {:id => learning_group.to_param}, valid_session
      response.should redirect_to(learning_groups_url)
    end
  end

end
